<font color = green >

# Numpy
</font>

In [1]:
import numpy as np 

<font color = green >

## array
</font>

In [2]:
x = np.array([1,2,3,4])
print (type(x))
x

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [3]:
y = np.array([[7, 8, 9], [10, 11, 12]])
y

array([[ 7,  8,  9],
       [10, 11, 12]])

<font color = green >

### Shape
</font>

In [4]:
y.shape

(2, 3)

<font color = green >

### arange
</font>

In [5]:
?range

In [6]:
print (np.array(range(2,10,3)))
np.arange(2,10,3)

[2 5 8]


array([2, 5, 8])

<font color = green >

### linspace
</font>

In [7]:
np.linspace(1,10,5)


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

<font color = green >

### logspace
</font>

In [8]:
np.logspace(-1, 3, 5)

array([1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

<font color = green >

### Reshape
</font>

In [9]:
a= np.arange (0,20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
b = a.reshape(4,5) # Note it is not inplace operation
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
a.reshape(5,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
a.resize(2,10) # Note: This is inplace operation
a
# Note: negative dimensions not allowed

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

<font color = green >

### zeros/ones/eye
</font>

In [13]:
a= np.zeros(3)
print (a.dtype)
a

float64


array([0., 0., 0.])

In [14]:
np.zeros([2,2,3]).astype(int) # dtype float by default

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [15]:
print (np.ones(4, int)) # pass type into creation function
np.eye(3)

[1 1 1 1]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<font color = green >

### diag
</font>

In [16]:
a= np.arange (0,9)
a.resize(3,3)
diag= np.diag(a)
a


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
diag

array([0, 4, 8])

In [18]:
print (np.repeat([1,2,3],3))
print (np.array([1,2,3]*3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


***
<font color = green >

## broadcast operations
</font>

In [19]:
x= np.eye(3)
y = np.ones(3)
x+y

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [20]:
a= np.array([1,2,3])
print (a+1)
print (a*3)
print (a**2)


[2 3 4]
[3 6 9]
[1 4 9]


<font color = green >

### combine arrays
</font>

In [21]:
np.append([[1, 2, 3], [4, 5, 6]], [7, 8])
# Note: without axis value it makes both flattened before append

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
# setting axis
np.append([[1, 2, 3], [4, 5, 6]], [[7], [8]], axis= 1)


array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [23]:
x= np.array ([[1,2], [3,4]])
y= np.array ([[5,6], [7,8]])

In [24]:
np.concatenate((x,y)) # Note  double brackets

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
np.concatenate((x,y), axis= 1) 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [26]:
np.hstack((x,y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [27]:
np.c_[x,y] # alternative for axis 1 
# the same as np.hstack((x,y)) 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [28]:
np.r_[x,y] # alternative for axis 0
# the same as  np.vstack((x,y))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

<font color = green >

### Multiply arrays
</font>

<font color = green >

### Element-wise
</font>

In [29]:
x= np.array ([[1,2], [3,4]])
y= np.array ([[5,6], [7,8]])

x*y 
# the same as np.multiply(x, y)

array([[ 5, 12],
       [21, 32]])

<font color = green >

### Matrix multiplication
</font>

In [30]:
print (x,'\n\n' , y, '\n', '='*20)
x @ y 
# the same as np.matmul(x,y)
# Note about number of rows and columns

[[1 2]
 [3 4]] 

 [[5 6]
 [7 8]] 


array([[19, 22],
       [43, 50]])

<font color = green >


### dot
</font>

In [31]:
np.dot ([1,2,3], [2,4,5]) # inner product - case of 1d arrays (vectors)
# the same as np.sum(np.array([1,2,3]) @ np.array([2,4,5]).T)

25

In [32]:
np.dot (x,y) # matmul - case of 2d arrays (matrices)
# x@y  is prefered 

array([[19, 22],
       [43, 50]])

In [33]:
np.dot ([1,2,3], 5) # broadcast multiplication - case one of arguments is scalar
# x*y  is prefered 

array([ 5, 10, 15])

***
<font color = green >

## slicing arrays
</font>


<font color = green >

### slicing 1D arrays
</font>

In [34]:
a = np.array([1,2,3,4,5,6]) 
print (a)
print (a[::-1], 'all items in the array, reversed:')
# default values print (a[-1:-7:-1])

print (a[1::-1], 'the first two items, reversed:')
print (a[:-3:-1],'the last two items, reversed:') 
print (a[-3::-1],'everything except the last two items, reversed:' )

[1 2 3 4 5 6]
[6 5 4 3 2 1] all items in the array, reversed:
[2 1] the first two items, reversed:
[6 5] the last two items, reversed:
[4 3 2 1] everything except the last two items, reversed:



<font color = green >

### slicing ndarrays
</font>

In [35]:
a= np.arange(20).reshape(5,-1)
print (a,'\n', '='*15)
a [:,1:3]        

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 


array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [36]:
a [3,1:3]   = -1
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, -1, -1, 15],
       [16, 17, 18, 19]])

<font color = green >

### Quering arrays
</font>

In [37]:
a>10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True, False, False,  True],
       [ True,  True,  True,  True]])

In [38]:
print (a>9)
a[a>9] # Note: Returns flattened if bolean mask provided as index

[[False False False False]
 [False False False False]
 [False False  True  True]
 [ True False False  True]
 [ True  True  True  True]]


array([10, 11, 12, 15, 16, 17, 18, 19])

<font color = green >

### argmin/argmax
</font>

In [39]:
a = np.array([
    [2,1,4], 
    [-1,8,2],
    [6,0,1]])
print (a.argmin()) # Note returns the index of first el in flattened array in case axis is not provided 
print (a.argmin(axis= 0), 'axis= 0 means vertically  - for every column')
print (a.argmax(axis= 1), 'axis= 1 means horizontally  - for every row')

3
[1 2 2] axis= 0 means vertically  - for every column
[2 1 0] axis= 1 means horizontally  - for every row


<font color = green >

### Where
</font>

In [40]:
x = np.array([[1,7],[8,3], [1,3]])
np.where(x < 5, x, -1)  # broadcast condition

array([[ 1, -1],
       [-1,  3],
       [ 1,  3]])

In [41]:
# element-wise condition
np.where([[True, False], [True, True]],[[1, 2], [3, 4]], [[5, 6], [7, 8]]) 
# [[1, 2], [3, 4]] is used for True located elements  
#  [[5, 6], [7, 8]] is used for False  located elements  

array([[1, 6],
       [3, 4]])

In [42]:
print (f'x=\n{x}\n')

print ('x[x > 2]=', x[x > 2])
x [np.where( x > 2)] # actually gives the same result as  x[x > 3] 

print ('\nNote:  x>2  is boolean mask :  [[False,  True], [ True, True], [False, False]]\n'\
       'but np.where( x > 3) returns tuple: (array([0, 1, 1, 2]), array([1, 0, 1, 1]))\n'\
       'which contains indices of  element True')


x=
[[1 7]
 [8 3]
 [1 3]]

x[x > 2]= [7 8 3 3]

Note:  x>2  is boolean mask :  [[False,  True], [ True, True], [False, False]]
but np.where( x > 3) returns tuple: (array([0, 1, 1, 2]), array([1, 0, 1, 1]))
which contains indices of  element True


<font color = green >

### Unique
</font>

In [43]:
print (f'x=\n{x}\n')
np.unique(x)

x=
[[1 7]
 [8 3]
 [1 3]]



array([1, 3, 7, 8])

***
<font color = green >

## linalg
</font>


<font color = green >

### Solve
</font>

In [44]:
a=np.array([[1,2,3],[0,1,2], [2,0,0]])
b = [1,1,0]
np.linalg.solve (a,b)

array([ 0., -1.,  1.])

### Determinant

In [45]:
a_sing=np.array([[1,2,3],[0,1,2], [1,3,5]])
np.linalg.det(a_sing)

0.0


<font color = green >

### Inverse matrix
</font>

In [46]:
print ('a=\n',a,'\n','='*10)
print ('inv(a):\n',np.linalg.inv (a)) 
print ('='*10,'\nto compare with pseudo-inv(a):\n', np.linalg.pinv (a)) # pseudo-inverse of a matrix is defined as: “the matrix that ‘solves’ [the least-squares problem] 
print ('pinv returns the inverse of your matrix when it is available and the pseudo inverse when it isn\'t.')
print ('='*10,'\n',np.linalg.pinv (a) @ a)

print ('='*10,'\na_singular=\n',a_sing,'\n')
try: 
    np.linalg.inv (a_sing)
except Exception as e:
    print ('Exception:',e)
print ('='*10,'\npseudo-inv(a_singular):\n', np.linalg.pinv (a_sing))
np.linalg.pinv (a_sing) @ a_sing


a=
 [[1 2 3]
 [0 1 2]
 [2 0 0]] 
inv(a):
 [[ 0.   0.   0.5]
 [ 2.  -3.  -1. ]
 [-1.   2.   0.5]]
to compare with pseudo-inv(a):
 [[ 2.01529919e-16 -9.51793928e-17  5.00000000e-01]
 [ 2.00000000e+00 -3.00000000e+00 -1.00000000e+00]
 [-1.00000000e+00  2.00000000e+00  5.00000000e-01]]
pinv returns the inverse of your matrix when it is available and the pseudo inverse when it isn't.
 [[ 1.00000000e+00  3.07880444e-16  4.14230970e-16]
 [-8.88178420e-16  1.00000000e+00  2.66453526e-15]
 [ 2.22044605e-16 -2.22044605e-16  1.00000000e+00]]
a_singular=
 [[1 2 3]
 [0 1 2]
 [1 3 5]] 

Exception: Singular matrix
pseudo-inv(a_singular):
 [[ 1.00000000e+00 -1.16666667e+00 -1.66666667e-01]
 [ 3.33333333e-01 -3.33333333e-01  1.04083409e-16]
 [-3.33333333e-01  5.00000000e-01  1.66666667e-01]]


array([[ 0.83333333,  0.33333333, -0.16666667],
       [ 0.33333333,  0.33333333,  0.33333333],
       [-0.16666667,  0.33333333,  0.83333333]])


<font color = green >

### Norm
</font>

In [47]:
a = np.array ([3,4])
np.linalg.norm(a)

5.0

***
<font color = green >

## Other functions
</font>

In [48]:
a = [1]*10 + list(range(10,15))
print ('a=', a)
print ('np.mean(a)=', np.mean(a))
print ('np.std(a)=', np.std(a))
print ('np.median(a)=', np.median(a))
print ('np.sum(a)=', np.sum(a))
print ('np.min(a)=', np.min(a))

a= [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 10, 11, 12, 13, 14]
np.mean(a)= 4.666666666666667
np.std(a)= 5.2493385826745405
np.median(a)= 1.0
np.sum(a)= 70
np.min(a)= 1


In [49]:
a= np.arange(10)
print (a)
np.random.shuffle(a)
print (a)

[0 1 2 3 4 5 6 7 8 9]
[4 5 2 8 1 6 7 0 9 3]


In [50]:
from scipy import stats # To get all characteristic at once 
stats.describe(a)

DescribeResult(nobs=10, minmax=(0, 9), mean=4.5, variance=9.166666666666666, skewness=0.0, kurtosis=-1.2242424242424244)


<font color = green >

### Cumulative sum
</font>

In [51]:
a= np.array([[1,2,3], [4,5,6]])
print (a)
print  (np.cumsum(a)) # element wise by default 
print (np.cumsum(a,0)) # axis =0
np.cumsum(a,1) # axis =1

[[1 2 3]
 [4 5 6]]
[ 1  3  6 10 15 21]
[[1 2 3]
 [5 7 9]]


array([[ 1,  3,  6],
       [ 4,  9, 15]])

***
<font color = green >

## apply operations
</font>

<font color = green >

### apply_along_axis 
</font>

In [52]:
print (a)
print ('\n',np.apply_along_axis(np.sum,0,a)) # axis 0 , 
np.apply_along_axis(np.sum,1,a) # axis 1 

[[1 2 3]
 [4 5 6]]

 [5 7 9]


array([ 6, 15])

<font color = green >

### vectorize
</font>

In [53]:
def func(x):
    return x+1 if x%2 ==0 else -1

In [54]:
v_func = np.vectorize (func)
v_func(a)

array([[-1,  3, -1],
       [ 5, -1,  7]])

***
<font color = green >

## Random
</font>

In [55]:
import numpy as np
a = np.random.randint(0,10, size= (3, 4)) # (low, high=None, size=None)
a

array([[5, 0, 0, 9],
       [6, 7, 6, 3],
       [9, 1, 0, 7]])

In [56]:
np.random.randint(2, size = 10) # Note: is None (the default), then results are from [0, low).

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 0])

In [57]:
np.random.randn(3,4) # normal distribution

array([[-0.88927041, -1.0577994 , -1.38379131,  2.04677032],
       [-1.58320243, -1.17405021,  0.92902609, -1.19343886],
       [-0.89941609,  0.04356407, -0.1771949 ,  0.54044041]])

In [58]:
np.random.normal(loc=3, scale=4, size=(2,4)) # similar to randn but accepts more params 

array([[ 5.13739221,  7.86715227,  9.949398  , -3.39991956],
       [ 3.22387768, -1.86842686, -6.94964949,  1.43312341]])


<font color = green >

### Sampling
</font>

In [59]:
pvals= [.5, .5] # (n, pvals, size=None)
np.random.multinomial(1000, pvals, 3)  # n flips in each of "size' samples 

array([[492, 508],
       [505, 495],
       [506, 494]])

In [60]:
pvals= [.1, .3, .6] # (n, pvals, size=None)
np.random.multinomial(1000, pvals, 5)

array([[110, 318, 572],
       [ 90, 295, 615],
       [ 91, 294, 615],
       [ 99, 310, 591],
       [ 98, 305, 597]])

In [61]:
np.random.multinomial(10, pvals, 1)

array([[0, 2, 8]])

In [62]:
pvals= [.1, .3, .6] # (n, pvals, size=None)
np.sum(np.random.multinomial(1, pvals, 1000), axis= 0) # the same as  np.random.multinomial(1000, pvals, 1)

array([101, 328, 571])

In [63]:
a = np.random.randint(0,10, size= (3, 4)) # (low, high=None, size=None)
print (a)
np.random.shuffle(a) # Note: inplace operation
a

[[4 5 8 4]
 [5 3 0 9]
 [2 5 5 9]]


array([[2, 5, 5, 9],
       [4, 5, 8, 4],
       [5, 3, 0, 9]])

In [64]:
b = np.random.permutation(a)  # Alternative not-inplace  operation for shuffle 
b

array([[2, 5, 5, 9],
       [4, 5, 8, 4],
       [5, 3, 0, 9]])

In [65]:
np.random.permutation(7) # for integer np.random.shuffle(np.arange(n))

array([4, 2, 0, 3, 5, 6, 1])

In [66]:
np.random.seed(1) # to get the same sequence of random values 

print (np.random.permutation(5))
print (np.random.permutation(5))
np.random.seed(1) # 
print (np.random.permutation(5))
print (np.random.permutation(5))

[2 1 4 0 3]
[0 2 4 3 1]
[2 1 4 0 3]
[0 2 4 3 1]


<font color = green >

### Learn more
</font>

NumPy Reference
<br>https://docs.scipy.org/doc/numpy-1.13.0/reference/
<br>Numpy cheat sheet
<br>https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf






# Home task 

## Task about sum and product 

```
There are two whole numbers:
1 < a,b <100

One scientist("Sum") get provided with sum of numbers,
another  ("Prod") get provided with product of numbers. 
Both scientists know that numbers 1 < a,b <100.

Determine the numbers being based on the following dialog: 
    Prod: I don't know the numbers;
    Sum: I know it;
    Prod: then I know the numbers; 
    Sum: then I know the numbers too.
```

Next: lesson_3_part_pandas.ipynb